-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 15:20:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ems
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ems
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ems` DEFAULT CHARACTER SET utf8 ;
USE `ems` ;

-- -----------------------------------------------------
-- Table `ems`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ems`.`room` (
  `room_no` INT NOT NULL,
  `room_location` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`room_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ems`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ems`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pos_name` VARCHAR(25) NOT NULL,
  `pos_des` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ems`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ems`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dept_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ems`.`ticket_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ems`.`ticket_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ems`.`ticket_description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ems`.`ticket_description` (
  `id` INT NOT NULL,
  `tickd_statement` VARCHAR(255) NOT NULL,
  `tickd_limit` TIME NOT NULL,
  `tickd_status` VARCHAR(10) NOT NULL,
  `tickd_priority` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ems`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ems`.`employee` (
  `id` INT NOT NULL,
  `emp_lname` VARCHAR(20) NOT NULL,
  `emp_fname` VARCHAR(20) NOT NULL,
  `emp_mname` VARCHAR(20) NOT NULL,
  `emp_contact_no` VARCHAR(15) NOT NULL,
  `position_id` INT NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_position1_idx` (`position_id` ASC),
  INDEX `fk_employee_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_employee_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `ems`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `ems`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ems`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ems`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `auth_key` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `password_reset_token` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `status` SMALLINT(6) NOT NULL,
  `created_at` INT NOT NULL,
  `updated_at` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_user_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `ems`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ems`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ems`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tick_closed_time` DATETIME NULL,
  `tick_date` DATETIME NOT NULL,
  `tick_escalate` TINYINT NOT NULL,
  `room_id` INT NOT NULL,
  `ticket_type_id` INT NOT NULL,
  `ticket_description_id` INT NOT NULL,
  `department_id` INT NOT NULL,
  `room_room_no` INT NOT NULL,
  `user_id` INT NULL,
  `user_id1` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_ticket_type1_idx` (`ticket_type_id` ASC),
  INDEX `fk_ticket_ticket_description1_idx` (`ticket_description_id` ASC),
  INDEX `fk_ticket_department1_idx` (`department_id` ASC),
  INDEX `fk_ticket_room1_idx` (`room_room_no` ASC),
  INDEX `fk_ticket_user1_idx` (`user_id` ASC),
  INDEX `fk_ticket_user2_idx` (`user_id1` ASC),
  CONSTRAINT `fk_ticket_ticket_type1`
    FOREIGN KEY (`ticket_type_id`)
    REFERENCES `ems`.`ticket_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_ticket_description1`
    FOREIGN KEY (`ticket_description_id`)
    REFERENCES `ems`.`ticket_description` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `ems`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_room1`
    FOREIGN KEY (`room_room_no`)
    REFERENCES `ems`.`room` (`room_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ems`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_user2`
    FOREIGN KEY (`user_id1`)
    REFERENCES `ems`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ems`.`hierarchy_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ems`.`hierarchy_level` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level_num` VARCHAR(1) NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hierarchy_level_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_hierarchy_level_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `ems`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ems`.`escalated_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ems`.`escalated_ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `esc_date_received` DATE NOT NULL,
  `esc_time_received` TIME NOT NULL,
  `esc_reason` VARCHAR(50) NOT NULL,
  `esc_owner` VARCHAR(45) NOT NULL,
  `esc_level` VARCHAR(1) NOT NULL,
  `esc_status` VARCHAR(10) NOT NULL,
  `esc_priority` VARCHAR(10) NOT NULL,
  `esc_time_closed` TIME NOT NULL,
  `esc_date_closed` DATE NOT NULL,
  `hierarchy_level_id` INT NOT NULL,
  `ticket_description_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_escalated_ticket_hierarchy_level1_idx` (`hierarchy_level_id` ASC),
  INDEX `fk_escalated_ticket_ticket_description1_idx` (`ticket_description_id` ASC),
  CONSTRAINT `fk_escalated_ticket_hierarchy_level1`
    FOREIGN KEY (`hierarchy_level_id`)
    REFERENCES `ems`.`hierarchy_level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escalated_ticket_ticket_description1`
    FOREIGN KEY (`ticket_description_id`)
    REFERENCES `ems`.`ticket_description` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
